Main: Lox.java
	javac -cp Lox Lox.java Scanner.java Token.java TokenType.java Parser.java Expr.java Interpreter.java RuntimeError.java Stmt.java Environment.java LoxFunction.java LoxCallable.java Exceptions.java Resolver.java

run:
	@java lox.Lox
